spring:
  profiles:
    active: database

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  mvc:
    async:
      request-timeout: 160000

logging.level:
  org.hibernate.SQL: debug
